# Generated by Django 5.2.6 on 2026-07-22 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('references', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory_number', models.CharField(max_length=100, unique=True, verbose_name='Заводской номер машины')),
                ('engine_number', models.CharField(max_length=100, verbose_name='Заводской номер двигателя')),
                ('transmission_number', models.CharField(max_length=100, verbose_name='Заводской номер трансмиссии')),
                ('drive_axle_number', models.CharField(max_length=100, verbose_name='Заводской номер ведущего моста')),
                ('steering_axle_number', models.CharField(max_length=100, verbose_name='Заводской номер управляемого моста')),
                ('supply_contract', models.CharField(max_length=255, verbose_name='Договор поставки')),
                ('shipment_date', models.DateField(verbose_name='Дата отгрузки с завода')),
                ('consignee', models.CharField(max_length=255, verbose_name='Грузополучатель')),
                ('delivery_address', models.CharField(max_length=255, verbose_name='Адрес поставки')),
                ('equipment', models.TextField(blank=True, verbose_name='Комплектация')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_machines', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('drive_axle_model', models.ForeignKey(limit_choices_to={'entity_name': 'drive_axle_model'}, on_delete=django.db.models.deletion.PROTECT, related_name='drive_axle_models', to='references.reference', verbose_name='Модель ведущего моста')),
                ('engine_model', models.ForeignKey(limit_choices_to={'entity_name': 'engine_model'}, on_delete=django.db.models.deletion.PROTECT, related_name='engine_models', to='references.reference', verbose_name='Модель двигателя')),
                ('machine_model', models.ForeignKey(limit_choices_to={'entity_name': 'machine_model'}, on_delete=django.db.models.deletion.PROTECT, related_name='machine_models', to='references.reference', verbose_name='Модель техники')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_company_machines', to=settings.AUTH_USER_MODEL, verbose_name='Сервисная компания')),
                ('steering_axle_model', models.ForeignKey(limit_choices_to={'entity_name': 'steering_axle_model'}, on_delete=django.db.models.deletion.PROTECT, related_name='steering_axle_models', to='references.reference', verbose_name='Модель управляемого моста')),
                ('transmission_model', models.ForeignKey(limit_choices_to={'entity_name': 'transmission_model'}, on_delete=django.db.models.deletion.PROTECT, related_name='transmission_models', to='references.reference', verbose_name='Модель трансмиссии')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
                'ordering': ['shipment_date'],
            },
        ),
    ]
