# Generated by Django 5.2.6 on 2026-07-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='buyer',
            field=models.CharField(default='Не указан', max_length=255, verbose_name='Покупатель'),
            preserve_default=False,
        ),
    ]
