# Generated by Django 5.2.6 on 2026-07-23 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenance',
            options={'ordering': ['maintenance_date'], 'verbose_name': 'Техническое обслуживание', 'verbose_name_plural': 'Технические обслуживания'},
        ),
        migrations.AddField(
            model_name='maintenance',
            name='maintenance_type',
            field=models.ForeignKey(default=1, limit_choices_to={'entity_name': 'maintenance_type'}, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_types', to='references.reference', verbose_name='Вид ТО'),
            preserve_default=False,
        ),
    ]
