# Generated by Django 5.2.6 on 2026-07-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(choices=[('machine_model', 'Модель техники'), ('engine_model', 'Модель двигателя'), ('transmission_model', 'Модель трансмиссии'), ('drive_axle_model', 'Модель ведущего моста'), ('steering_axle_model', 'Модель управляемого моста'), ('maintenance_type', 'Вид ТО'), ('service_company', 'Сервисная компания'), ('failure_node', 'Узел отказа'), ('recovery_method', 'Способ восстановления'), ('maintenance_company', 'Организация, проводившая ТО')], max_length=50, verbose_name='Название сущности')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Справочник',
                'verbose_name_plural': 'Справочники',
                'ordering': ('entity_name', 'name'),
            },
        ),
    ]
